// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProtectGaia.DataContexts;

namespace ProtectGaia.Migrations
{
    [DbContext(typeof(ChallengeDB))]
    [Migration("20200518143345_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProtectGaia.Models.ChallengeModel", b =>
                {
                    b.Property<int>("CarbonScore")
                        .HasColumnType("int");

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<string>("ChallengeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ChallengeData");
                });

            modelBuilder.Entity("ProtectGaia.Models.UserModel", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarbonActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarbonScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsFirstTimeLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTask1Completed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTask2Completed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTask3Completed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTask4Completed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTask5Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("LevelCompletedTask")
                        .HasColumnType("int");

                    b.Property<int>("PendingTask")
                        .HasColumnType("int");

                    b.Property<int>("TotalPointScored")
                        .HasColumnType("int");

                    b.Property<int>("TotalTaskCompleted")
                        .HasColumnType("int");

                    b.Property<string>("UserImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("UserEmail", "LevelId");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
