// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProtectGaia.DataContexts;

namespace ProtectGaia.Migrations
{
    [DbContext(typeof(ChallengeDB))]
    partial class ChallengeDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ProtectGaia.Models.ChallengeModel", b =>
                {
                    b.Property<string>("ChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarbonScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChallengeTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChallengeId");

                    b.ToTable("ChallengeData");
                });

            modelBuilder.Entity("ProtectGaia.Models.UserModel", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activity")
                        .HasColumnType("TEXT");

                    b.Property<int>("CarbonScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTask1Completed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTask2Completed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTask3Completed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTask4Completed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTask5Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelCompletedTask")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingTask")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPointScored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTaskCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("UserEmail", "LevelId");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
